version: 2.0
references:
  JOB_DEFAULTS: &JOB_DEFAULTS
    working_directory: &WORKING_DIRECTORY ~/website
    docker:
      - image: circleci/ruby:2.5-node

  RESTORE_CACHE: &RESTORE_CACHE
    restore_cache:
      keys:
        - &BUNDLER_CACHE_KEY v1-bundler-cache-{{ checksum "Gemfile.lock" }}
        - v1-bundler-cache

  SAVE_CACHE: &SAVE_CACHE
    save_cache:
      key: *BUNDLER_CACHE_KEY
      paths:
        - vendor/bundle
  RUN_BUNDLE_INSTALL: &RUN_BUNDLE_INSTALL
    run:
      name: Install dependencies using bundler
      command: |
        bundle check --path=vendor/bundle || \
        bundle install --frozen --path=vendor/bundle --jobs=4 --retry=3

jobs:
  build:
    <<: *JOB_DEFAULTS
    steps:
      - checkout
      - *RESTORE_CACHE
      - *RUN_BUNDLE_INSTALL
      - *SAVE_CACHE
      - run:
          name: Build website using jekyll
          command: JEKYLL_ENV=production bundle exec jekyll build

      - persist_to_workspace:
          root: "."
          paths:
            - _site

  checks:
    <<: *JOB_DEFAULTS
    steps:
      - checkout
      - *RESTORE_CACHE
      - *RUN_BUNDLE_INSTALL
      - *SAVE_CACHE
      - run:
          name: Check for vulnerabilities using bundler-audit
          command: bundle exec bundle-audit check --update
      - run:
          name: Run spell check
          command: |
            npx -p markdown-spellcheck mdspell -a -n -r "index.md" "pages/*.md" || true

  deploy:
    <<: *JOB_DEFAULTS
    steps:
      - attach_workspace:
          at: &WORKSPACE_DIR /tmp/workspace
      - deploy:
          name: Deploy to S3
          environment:
            WORKSPACE_DIR: *WORKSPACE_DIR
          command: |
            cd "$WORKSPACE_DIR"
            sudo apt-get -y -qq update
            sudo apt-get -y -qq install awscli
            aws s3 sync _site/ s3://rotemaf.info/ --delete --cache-control "public, max-age=30"
workflows:
  version: 2
  release:
    jobs:
      - build
      - checks:
          requires: ["build"]
      - deploy:
          requires: ["build"]
          filters: { branches: { only: master } }
