version: 2
references:
  JOB_DEFAULTS: &JOB_DEFAULTS
    working_directory: &WORKING_DIRECTORY ~/website
    docker:
      - image: circleci/ruby:2.5-node

jobs:
  build:
    <<: *JOB_DEFAULTS
    steps:
      - checkout
      - run:
          name: Install dependencies using bundler
          command: |
            bundle check --path=vendor/bundle || \
            bundle install --frozen --path=vendor/bundle --jobs=4 --retry=3

      - run:
          name: Check for vulnerabilities using bundler-audit
          command: bundle exec bundle-audit check --update

      - run:
          name: Build website using jekyll
          command: JEKYLL_ENV=production bundle exec jekyll build

      - run:
          name: This is where we run spellcheck, link checker, ...
          command: |
            echo "If you're happy and you know it clap your hands!!!"

      - persist_to_workspace:
          root: "."
          paths:
            - _site
  deploy:
    <<: *JOB_DEFAULTS
    steps:
      - attach_workspace:
          at: &WORKSPACE_DIR /tmp/workspace
      - deploy:
          name: Deploy to S3
          environment:
            WORKSPACE_DIR: *WORKSPACE_DIR
          command: |
            if [[ "$CIRCLE_BRANCH" == "master" ]]; then
              cd "$WORKSPACE_DIR"
              sudo apt-get -y -qq update
              sudo apt-get -y -qq install awscli
              aws s3 sync _site/ s3://rotemaf.info/ --delete --cache-control "public, max-age=30"
            else
              echo "Not master. Skipping deployment"
            fi
workflows:
  version: 2
  release:
    jobs:
      - build
      - deploy:
          requires: ["build"]
